### ISSUE TITLE
[Question] Original names of missing Headers

### ISSUE THREAD

**Issue by Piioo** [tilo/smarter_csv#271]
Hello,

how do I get the original names of the missing header columns?

SmarterCSV::MissingKeys contains a message but not the keys and not the original keys.

**Comment by tilo** [comment]
🤔 the missing keys should be added to the message.. https://github.com/tilo/smarter_csv/blob/5e3be6777eeb6e08980369ad83681baf158d5bea/lib/smarter_csv/header_validations.rb#L29

@Piioo Can you please provide a simple CSV file that reproduces the issue, along with the options you're using?

**Comment by tilo** [comment]
thank you for explaining! 

this is a bit tricky, because the `required_keys` are what is expected after mapping of headers. The code just knows that you expect `:three` and raises the error that it is missing.
This part of the code does not understand what the original CSV-header was named.

You can get to the original headers from the CSV-file via `SmarterCSV.headers`.

Does that work for you?

**Comment by tilo** [comment]
I added this to the error message:

https://github.com/tilo/smarter_csv/blob/303c703c6635ae117c1c777b102c9c7e9d672e8c/lib/smarter_csv/header_validations.rb#L29

**Comment by tilo** [comment]
@Piioo version 1.10.2 has the improved error message

https://github.com/tilo/smarter_csv/pull/272

**Comment by Piioo** [comment]
Thanks you very much :)
